version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "10:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "10:30"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
