version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: scrollreveal
    versions:
    - 4.0.8
  - dependency-name: marked
    versions:
    - 2.0.1
  - dependency-name: npm-force-resolutions
    versions:
    - 0.0.5
